// 캡처 시 함께 기록할 강조 영역. [key, 엘리먼트 표현식, 번호 뱃지 방향]
// __h.t(텍스트) = 버튼/링크 탐색, __h.q(선택자), __h.qa(선택자, 인덱스)
export const SPEC = {
  '01_login': [['login', `__h.t('로그인','button[type=submit]')`, 'right'], ['demo', `__h.t('데모 계정으로 체험하기')`, 'right'], ['signup', `__h.q('.page-auth a')`, 'right']],
  '01b_login_error': [['error', `__h.q('.error-text')`, 'right'], ['login', `__h.t('로그인','button[type=submit]')`, 'right']],
  '02_signup_error': [['error', `__h.q('.error-text')`, 'right'], ['submit', `__h.t('가입하기')`, 'right']],
  '03_home_empty_pick': [['count', `__h.q('.hint-text')`, 'right'], ['draw', `__h.t('AI 오늘의 픽 받기')`, 'right']],
  '04_home_drawn': [['lock', `__h.q('.lock-btn')`, 'left'], ['reroll', `__h.t('다시 돌리기')`, 'left'], ['confirm', `__h.t('이걸로 입을래요')`, 'right']],
  '05_home_confirmed': [['chip', `__h.q('.chip')`, 'right'], ['detail', `__h.t('상세 보기')`, 'left'], ['change', `__h.t('다른 코디로 바꾸기')`, 'right']],
  '06_wardrobe': [['filters', `__h.q('.filters')`, 'right'], ['card', `__h.q('.clothing-card')`, 'left'], ['fab', `__h.q('.fab')`, 'left']],
  '06b_wardrobe_filter': [['filters', `__h.q('.filters')`, 'right'], ['reset', `__h.t('필터 초기화')`, 'right']],
  '07_wardrobe_add_sheet': [['photo', `__h.t('사진으로 등록')`, 'right'], ['text', `__h.t('문장으로 여러 벌 등록')`, 'right'], ['manual', `__h.t('직접 입력으로 등록')`, 'right']],
  '08a_add_photo_empty': [['pick', `__h.t('사진 선택하기')`, 'right'], ['limit', `__h.qa('.empty-state p', 1)`, 'left']],
  '08b_add_photo_result': [['result', `__h.q('.section-title')`, 'right'], ['save', `__h.t('이 정보로 저장')`, 'right']],
  '09_add_photo_fail': [['error', `__h.q('.error-text')`, 'right'], ['manual', `__h.t('수동 등록으로 이동')`, 'right']],
  '10_add_text_candidates': [['analyze', `__h.t('AI로 분석하기')`, 'right'], ['cand', `__h.qa('.card', 1)`, 'right'], ['save', `__h.t('일괄 저장')`, 'right']],
  '11_add_manual': [['photo', `__h.t('사진 추가 (선택)')`, 'right'], ['save', `__h.t('등록하기')`, 'right']],
  '12_clothing_detail': [['meta', `__h.q('.detail-row')`, 'right'], ['del', `__h.t('이 옷 삭제하기')`, 'right']],
  '13_outfits': [['ai', `__h.t('AI 추천')`, 'down'], ['manual', `__h.t('직접 만들기')`, 'down'], ['card', `__h.q('.outfit-card')`, 'right']],
  '14_outfit_ai_result': [['situation', `__h.q('textarea')`, 'right'], ['result', `__h.qa('.section-title', 0)`, 'right'], ['save', `__h.t('이 코디 저장하기')`, 'right']],
  '15_outfit_manual': [['order', `__h.t('↑')`, 'left'], ['select', `__h.q('.clothing-card.selected')`, 'right'], ['save', `__h.t('코디 저장하기')`, 'right']],
  '16_outfit_detail': [['reason', `__h.q('.detail-block')`, 'right'], ['place', `__h.t('플래너에 배치하기')`, 'right'], ['del', `__h.t('코디 삭제하기')`, 'right']],
  '17_planner': [['nav', `__h.q('.section-head')`, 'right'], ['filled', `[...document.querySelectorAll('.day-row')].find(r => !r.innerText.includes('+ 코디 배치하기'))`, 'right'], ['empty', `[...document.querySelectorAll('.day-row')].find(r => r.innerText.includes('+ 코디 배치하기'))`, 'right']],
  '18_planner_picker': [['title', `__h.q('.sheet .section-title')`, 'right'], ['card', `__h.q('.sheet .outfit-card')`, 'right']],
  '19_planner_action': [['replace', `__h.t('다른 코디로 교체')`, 'right'], ['unset', `__h.t('배치 해제')`, 'right']],
  '19b_planner_place_mode': [['banner', `__h.qa('.card', 0)`, 'right'], ['day', `__h.q('.day-row')`, 'right']],
  '20_planner_ai': [['request', `__h.t('주간 추천 요청')`, 'left'], ['days', `__h.qa('.card', 1)`, 'left'], ['save', `__h.t('플래너에 전체 저장')`, 'right']],
  '21_challenge_start': [['guide', `__h.q('.hint-text')`, 'right'], ['start', `__h.t('챌린지 시작하기')`, 'right']],
  '22_challenge_round': [['blur', `__h.q('input[type=checkbox]')`, 'right'], ['left', `__h.q('.pick-card')`, 'down']],
  '23_challenge_result': [['score', `__h.qa('.card', 1).firstElementChild`, 'right'], ['save', `__h.t('코디로 저장하기')`, 'right'], ['retry', `__h.t('다시 도전하기')`, 'right']],
  '24_settings_withdraw': [['warn', `[...document.querySelectorAll('.hint-text')].find(e => e.innerText.includes('복구'))`, 'right'], ['pw', `__h.q('input[type=password]')`, 'right'], ['submit', `__h.t('최종 탈퇴하기')`, 'right']],
}
